<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\user\Entity\User;

/**
 * Implements hook_theme().
 */
function blingby_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'blingby_dashboard' => [
      'variables' => [
        'videos' => NULL,
        'path' => NULL,
        'squadronRole' => NULL,
        'users' => NULL,
        'searchRecruiter' => NULL,
        'searchTitle' => NULL,
        'roles' => NULL,
        'uid' => NULL
      ],
      'template' => 'dashboard',
    ],
  ];
}
