<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function blingby_image_cropper_theme($existing, $type, $theme, $path) {
  return [
    'blingby_image_cropper' => [
      'variables' => [
        'image' => NULL,
        'path' => NULL,
      ],
      'template' => 'image-cropper',
    ],
    'blingby_image_tile_cropper' => [
      'variables' => [
        'image' => NULL,
      ],
      'template' => 'tile-image-cropper',
    ],
  ];
}


/**
 * Implements hook_form_alter().
 */
function blingby_image_cropper_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (in_array($form_id, ['node_video_edit_form', 'node_video_form'])) {
    $form['#attached']['library'][] = 'blingby_image_cropper/video';
  }
}